### PR TITLE
rescale scores from all runs with randomness and calculate mean and std

### PR DESCRIPTION
**Pull request by Flaminietta**
This PR arises from my wish to be able to plot not only the rough scores but also the normalized ones also in the case some randomness is added to the weights. If randomness is added to the weights, this means that MCD has N-input matrices and produces N-outputs.

The logic I have implemented is:
- one gets N-output matrices from the N-runs
- all matrices are rescaled between 0 and 1
- the mean is estimated from the rescaled matrices
- plot of normalized (i.e. rescaled) mean 
- the standard deviation of rescaled values is not statistically informative

This approach should retain the statistical properties of the rescaled values.

### CODE REVIEW

**Review by kapil-agnihotri — APPROVED** [review]
LGTM.
For your question, `What I can see is that the std of the rescaled scores looks like relatively bigger for the scores with lower values: does it make sense?` I am not very sure. Maybe it is because with randomised and normalised data you have more dense data and so is the difference in std.

**Review by mspada — APPROVED** [review]
Fine to me. About the question, I'm not sure why this is happening. Let me think a bit more about it

**Comment by Flaminietta** [comment]
> 

From the first to the second figure, the only thing changing is the rescaling before estimating the mean and std. Therefore, data density should be the same.

**Comment by Flaminietta** [comment]
> Fine to me. About the question, I'm not sure why this is happening. Let me think a bit more about it

I don't understand the behavior and think we should keep an eye on it (maybe also after merging). Actually, I'd expect a contrary behavior: if - by rescaling between 0 and 1 - we are reducing the range where the data is spread, I'd then expect a smaller standard deviation.

**Pull request merged**
